server:
  port: 8443
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: password
#    key-store-type: JKS
#    key-alias: mycert
#    enabled: on
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    #    url: jdbc:mysql://localhost:3308/shopapp?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    username: root
    #    password: P@ssw0rd
    password: ${DB_PASSWORD}    #    password: c@BM8pyyr!BBh$z
    url: jdbc:mysql://${IP_MYSQL}:3306/${DB_NAME}?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    #    username: ${DB_USER}

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 259200 #30 ngay
  secret_key: mlfpofQBNxVBBxFi2tWyB8CU6jbSR9HM

returnUrl: http://localhost:3000/momo/callback
notifyUrl: http://bombom.id.vn:3000/api/v1/payments/momo/callback
