server:
  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 1234
#    key-store-type: PKCS12
#    key-alias: myalias
#    enabled: true
spring:
  datasource:
    #    url: jdbc:mysql://sql.freedb.tech:3306/freedb_productdb?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3308/shopapp?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: P@ssw0rd
  #    username: freedb_user000000
  #    password: c@BM8pyyr!BBh$z
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 259200 #30 ngay
  secret_key: mlfpofQBNxVBBxFi2tWyB8CU6jbSR9HM
